# GitHub Labeler Configuration for Steel Browser
# This file is used by the actions/labeler@v5 action in pr-checks.yml

# Component labels based on file paths
api:
- changed-files:
  - any-glob-to-any-file: 'api/**/*'
  
ui:
- changed-files:
  - any-glob-to-any-file: 'ui/**/*'
  
documentation:
- changed-files:
  - any-glob-to-any-file: 
    - 'docs/**/*'
    - '*.md'
    - 'README.md'
    - 'CONTRIBUTING.md'
  
plugin-system:
- changed-files:
  - any-glob-to-any-file: 'api/src/services/cdp/plugins/**/*'
  
cdp:
- changed-files:
  - any-glob-to-any-file:
    - 'api/src/services/cdp/**/*'
    - 'api/src/modules/cdp/**/*'
  
session-management:
- changed-files:
  - any-glob-to-any-file:
    - 'api/src/services/session.service.ts'
    - 'api/src/modules/sessions/**/*'
  
file-storage:
- changed-files:
  - any-glob-to-any-file:
    - 'api/src/services/file.service.ts'
    - 'api/src/modules/files/**/*'

docker:
- changed-files:
  - any-glob-to-any-file:
    - 'docker-compose*.yml'
    - 'api/Dockerfile'
    - 'ui/Dockerfile'
    - '.dockerignore'

dependencies:
- changed-files:
  - any-glob-to-any-file:
    - 'package-lock.json'
    - '**/package-lock.json'
    - 'package.json'
    - '**/package.json'

github-actions:
- changed-files:
  - any-glob-to-any-file:
    - '.github/workflows/**/*'
    - '.github/**/*'

testing:
- changed-files:
  - any-glob-to-any-file:
    - '**/*.test.ts'
    - '**/*.test.js'
    - '**/*.spec.ts'
    - '**/*.spec.js'
    - 'tsconfig.test.json' 