services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - steel-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
      args:
        NODE_VERSION: 22.13.0
    ports:
      - "3000:3000"
      - "9223:9223"
    environment:
      - DOMAIN=${DOMAIN:-localhost:3000}
      - CDP_DOMAIN=${CDP_DOMAIN:-localhost:9223}
      - ENABLE_SESSION_PERSISTENCE=true
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./.cache:/app/.cache
    networks:
      - steel-network
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      redis:
        condition: service_healthy

  ui:
    build:
      context: .
      dockerfile: ./ui/Dockerfile
    ports:
      - "5173:80"
    environment:
      - API_URL=${API_URL:-http://api:3000}
    depends_on:
      - api
    networks:
      - steel-network
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  steel-network:
    name: steel-network
    driver: bridge

volumes:
  redis-data: