services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
      args:
        NODE_VERSION: 22.13.0
    ports:
      - "3000:3000"
      - "9223:9223"
      - "3001:3001"
      # - "10000-11000:10000-11000/udp" # Pion's ephemeral UDP ports for ICE
      - "10000-10010:10000-10010/udp"
      - "5004:5004/udp"
    environment:
      - DOMAIN=${DOMAIN:-localhost:3000}
      - CDP_DOMAIN=${CDP_DOMAIN:-localhost:9223}
      - ICE_SERVERS_JSON=${ICE_SERVERS_JSON:-[{"urls":["stun:stun.l.google.com:19302"]},{"urls":["stun:stun1.l.google.com:19302"]},{"urls":["stun:stun2.l.google.com:19302"]},{"urls":["stun:stun.relay.metered.ca:80"]},{"urls":["turn:standard.relay.metered.ca:80"], "username":"682a9f0e2d3dbb6e12d6d1f2","credential":"qbXBULME/7DxQA6X"},{"urls":["turn:standard.relay.metered.ca:80?transport=tcp"], "username":"682a9f0e2d3dbb6e12d6d1f2","credential":"qbXBULME/7DxQA6X"},{"urls":["turn:standard.relay.metered.ca:443"], "username":"682a9f0e2d3dbb6e12d6d1f2","credential":"qbXBULME/7DxQA6X"},{"urls":["turns:standard.relay.metered.ca:443?transport=tcp"], "username":"682a9f0e2d3dbb6e12d6d1f2","credential":"qbXBULME/7DxQA6X"}]}
      - EXTERNAL_IP=${EXTERNAL_IP:-$(curl -s ifconfig.me)}
    volumes:
      - ./.cache:/app/.cache
      - /tmp/.X11-unix:/tmp/.X11-unix
      - x11-auth:/tmp
      - recordings:/recordings
    networks:
      - steel-network

  ui:
    build:
      context: .
      dockerfile: ./ui/Dockerfile
    ports:
      - "5173:80"
    environment:
      - API_URL=${API_URL:-http://api:3000}
    depends_on:
      - api
    networks:
      - steel-network

volumes:
  x11-auth:
  recordings:

networks:
  steel-network:
    name: steel-network
    driver: bridge
