services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
      args:
        NODE_VERSION: 22.13.0
    ports:
      - "3000:3000"
      - "9223:9223"
    environment:
      - DOMAIN=${DOMAIN:-localhost:3000}
      - CDP_DOMAIN=${CDP_DOMAIN:-localhost:9223}
      - CHROME_HEADLESS=false
      - DISPLAY=:10
      - XAUTHORITY=/tmp/.Xauthority
    volumes:
      - ./.cache:/app/.cache
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # - x11-auth:/tmp
    networks:
      - steel-network

  ui:
    build:
      context: .
      dockerfile: ./ui/Dockerfile
    ports:
      - "5173:80"
    environment:
      - API_URL=${API_URL:-http://api:3000}
    depends_on:
      - api
    networks:
      - steel-network

networks:
  steel-network:
    name: steel-network
    driver: bridge
